Add DTLS PSK support
energostack/bisquitt pull request #70
Opened 2024-05-13 13:05 UTC by janvrska

### Summary:

Added support for PSK (DTLS preshared-key) in BISQUITT, enhancing security options. This feature integrates an HTTP API to obtain PSK keys, introducing API caching to optimize performance. With this update, users have the flexibility to choose between certificates and PSK for authentication, though both methods cannot be used simultaneously.

### Changes:

- Implemented PSK (DTLS preshared-key) support in BISQUITT.
- Integrated HTTP API for fetching PSK keys.
- Introduced API caching mechanism to reduce redundant API calls.
- Provided option for users to choose between certificates and PSK for authentication.

Notes:

- Users must select either certificates or PSK for authentication; simultaneous use of both methods is not supported.
- An example implementation of the HTTP API will be published in another repository following the BISQUITT release.

2024-05-13 15:14 UTC, JaSei requested changes

2024-05-13 15:14 UTC, JaSei commented on client/client.go
> +	PSKIdentity             string
Please use `PSKIdentityHint` in config as well to be consistent with the `dtls` library.

2024-05-13 15:14 UTC, JaSei commented on client/client.go
> +	resp, err := client.Do(req)
Just a hint - maybe timeout would be handy to be able to configure.

2024-05-13 15:14 UTC, JaSei commented on gateway/gateway.go
> +
This code duplicates the `client.go` you added. Can't we share it? PSK "client"?

2024-05-31 13:08 UTC, mprymek requested changes
I don't see any major issue in the code. I have a lot of comments but all are aesthetic only and most are just a matter of automatic refactoring...

It would be nice to have some tests by I don't see an easy way to write them...

2024-05-31 13:08 UTC, mprymek commented on cmd/bisquitt-sub/actions.go
> +			PSK:                     cache.New(pskCacheExpiration, 5*time.Minute),
Again: rather use `PSKKeys` for clarity?

2024-05-31 13:08 UTC, mprymek commented on cmd/bisquitt/actions.go
> +			PSK:                     cache.New(pskCacheExpiration, 5*time.Minute),
Again: rather use `PSKKeys` for clarity?

2024-05-31 13:08 UTC, mprymek commented on gateway/gateway.go
> +	PSK                     *cache.Cache
Again: rather use `PSKKeys` for clarity?

2024-05-31 13:08 UTC, mprymek commented on gateway/gateway.go
> +			if certificate = cfg.Certificate; certificate != nil {
Again: please split if to two lines for consistency with the above code.

2024-06-05 08:50 UTC, mprymek approved these changes

2024-06-06 09:05 UTC, JaSei approved these changes

2024-06-06 10:21 UTC, merged